from gen import Tree

trees = [
#0 simple test
Tree("root", 
     Tree("l"), 
     Tree("r")),

#1 deep left
Tree("root", 
  Tree("l1", 
    Tree("l2", 
      Tree("l3", 
        Tree("l4")))),
  Tree("r1")),

#2 deep right
Tree("root", 
  Tree("l1"),
  Tree("r1", 
    Tree("r2", 
      Tree("r3", 
        Tree("r4"))))
  ),

#3 tight right
Tree("root", 
  Tree("l1", 
    Tree("l2", 
      Tree("l3"), Tree("l4"))),
  Tree("r1", 
    Tree("rl1"),
    Tree("rr1", 
      Tree("rr2"), Tree("rr3")))),

#4 unbalanced
Tree("root", 
  Tree("l1", 
    Tree("l2", 
      Tree("l3", 
        Tree("l4", 
          Tree("l5"),
          Tree("l6")),
        Tree("l7")),
      Tree("l8")),
    Tree("l9")),
  Tree("r1", 
    Tree("r2", 
      Tree("r3"),
      Tree("r4")),
    Tree("r5"))),

#5 Wetherell-Shannon Tree
Tree("root",
  Tree("l1",
    Tree("ll1"),
    Tree("lr1",
      Tree("lrl"),
      Tree("lrr"))),
  Tree("r1",
    Tree("rr2",
      Tree("rr3",
        Tree("rrl",
          Tree("rrll",
            Tree("rrlll"),
            Tree("rrllr")),
          Tree("rrlr")))))),

#6 Buchheim Failure
Tree("root", 
  Tree("l",
    Tree("ll"),
      Tree("lr")),
  Tree("r", 
    Tree("rl"),
    Tree("rr"))),

#7 simple n-ary
Tree("root",
  Tree("l"),
  Tree("m"),
  Tree("r")),

#8 buchheim n-ary tree
#this works perfectly.
Tree("root",
  Tree("bigleft",
    Tree("l1"),
    Tree("l2"),
    Tree("l3"),
    Tree("l4"),
    Tree("l5"),
    Tree("l6"),
    Tree("l7", Tree("ll1"))),
  Tree("m1"),
  Tree("m2"),
  Tree("m3", Tree("m31")),
  Tree("m4"),
  Tree("bigright",
    Tree("brr",
      Tree("br1"),
      Tree("br2"),
      Tree("br3"),
      Tree("br4"),
      Tree("br5"),
      Tree("br6"),
      Tree("br7")))),

#9 random tree from http://www.brpreiss.com/books/opus5/html/page257.html
# so... the "tree to the right thing" is actually a bug
Tree("root",
  Tree("E",
    Tree("F",
      Tree("F1"),
      Tree("F2"),
      Tree("F3")),
    Tree("E2"),
    Tree("E3")),
  Tree("G",
    Tree("H",
      Tree("I",
        Tree("I1"),
        Tree("I2"),
        Tree("I3")),
      Tree("H2"),
      Tree("H3")),
    Tree("J",
      Tree("K",
        Tree("K1"),
        Tree("K2"),
        Tree("K3")),
      Tree("L",
        Tree("L1"),
        Tree("L2"),
        Tree("L3")),
      Tree("J3")),
    Tree("M",
      Tree("M1"),
      Tree("M2"),
      Tree("M3"))),
  Tree("D3")),

#10 big tree for testing
Tree("t", 
  Tree("rr", 
    Tree("rr1", 
      Tree("yy", 
        Tree("ab"), Tree("bc")), 
      Tree("zz", 
        Tree("a"), 
        Tree("b", 
          Tree("c"), 
          Tree("d", 
            Tree("e"), 
            Tree("f", 
              Tree("g"), 
              Tree("h",
                Tree("i"))))))), 
    Tree("rr2", Tree("rr22"))), 
  Tree("root",
    Tree("l1",
      Tree("ll1"),
      Tree("lr1",
        Tree("lrl"),
        Tree("lrr"))),
    Tree("r1",
      Tree("rr2",
        Tree("rr3",
          Tree("rrl",
            Tree("rrll",
              Tree("rrlll",
                Tree("98"), Tree("99")),
              Tree("rrllr")),
            Tree("rrlr"))))))),

#11 big tree for testing
Tree("欧",
    Tree("20/21",
         Tree("欧冠",
             Tree("西甲",
                  Tree("皇家马德里")),
             Tree("德甲",
                  Tree("拜仁慕尼黑"),
                  Tree("多特蒙德"),),
             Tree("英超",
                  Tree("曼城"),
                  Tree("利物浦"),
                  Tree("切尔西"),),
             Tree("意甲"),
             Tree("法甲",
                  Tree("巴黎"),),
             Tree("葡超",
                  Tree("波尔图"))),
         Tree("欧联",
             Tree("西甲",
                  Tree("比利亚雷亚尔"),
                  Tree("格拉纳达"),),
             Tree("德甲"),
             Tree("英超",
                  Tree("阿森纳"),
                  Tree("曼联"),),
             Tree("意甲",
                  Tree("罗马"),),
             Tree("法甲"),
             Tree("克甲",
                  Tree("萨格勒比迪纳摩")),
             Tree("荷甲",
                  Tree("阿贾克斯"),),
             Tree("捷甲",
                  Tree("布拉格斯拉维亚"),)),
              ),
    Tree("19/20",
         Tree("欧冠",
             Tree("西甲",
                  Tree("马德里竞技"),
                  Tree("巴塞罗那"),),
             Tree("德甲",
                  Tree("拜仁慕尼黑"),
                  Tree("莱比锡"),),
             Tree("英超",
                  Tree("曼城")),
             Tree("意甲",
                  Tree("亚特兰大"),),
             Tree("法甲",
                  Tree("巴黎"),
                  Tree("里昂"),)),
         Tree("欧联",
             Tree("西甲",
                  Tree("塞维利亚"),),
             Tree("德甲",
                  Tree("勒沃库森"),),
             Tree("英超",
                  Tree("狼队"),
                  Tree("曼联"),),
             Tree("意甲",
                  Tree("国际米兰"),),
             Tree("法甲"),
             Tree("瑞士超",
                  Tree("巴塞尔")),
             Tree("乌克超",
                  Tree("矿工"),),
             Tree("丹超",
                  Tree("哥本哈根"),),
              )),     
    Tree("18/19",
         Tree("欧冠",
             Tree("西甲",
                  Tree("巴塞罗那"),),
             Tree("德甲"),
             Tree("英超",
                  Tree("曼城"),
                  Tree("热刺"),
                  Tree("利物浦"),
                  Tree("曼联")),
             Tree("意甲",
                  Tree("尤文图斯"),),
             Tree("法甲"),
             Tree("葡超",
                  Tree("波尔图")),
             Tree("荷甲",
                  Tree("阿贾克斯"))),
         Tree("欧联",
             Tree("西甲",
                  Tree("瓦伦西亚"),
                  Tree("比利亚雷亚尔")),
             Tree("德甲",
                  Tree("法兰克福"),),
             Tree("英超",
                  Tree("阿森纳"),
                  Tree("切尔西"),),
             Tree("意甲",
                  Tree("那不勒斯"),),
             Tree("法甲"),
             Tree("葡超",
                  Tree("本菲卡")),
             Tree("捷甲",
                  Tree("布拉格斯拉维亚"))
              )) 
)
]